createdby            = "Araceli Vera"
deadline             = "5/8"
owner                = "Araceli Vera"
pod                  = "2"
project              = "Interno"
rg-name              = "rg-terraform-github-actions-demo-000"
location             = "eastus"
coe                  = "1"
